#!/usr/bin/env bash

FILE=$(osascript <<EOF 2>/dev/null
tell application "iTerm" to set sfile to choose file with prompt "Choose a file to send"
return POSIX path of sfile
EOF
)

if [[ -z "$FILE" ]]; then
  echo -e \\x18\\x18\\x18\\x18\\x18
else
  /opt/homebrew/bin/sz "$FILE" -E -e -b 2>/dev/null
fi

sleep 0.1
echo
